### ISSUE TITLE
herder pidfile

### ISSUE THREAD

**Issue by tbarbugli** [gds-operations/unicornherder#27]
Hi,
would you consider merge a PR that adds pidfile support for the herder process? I am using supervisord to manage the herder proc and I want to send HUP signals to it, supervisord does not have reload concept so I am sending a kill -HUP pid directly to herder proc (right now I need to use ps for that).

**Comment by rjw1** [comment]
We would certainly welcome a PR which adds pidfile support.  While we dont need it. We can see it being useful.
I would suggest making it an option so only people who need it get it.
